//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OkulOtomasyonu.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Dersler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dersler()
        {
            this.OgrenciDers = new HashSet<OgrenciDers>();
        }
    
        public int id { get; set; }
        [Required(ErrorMessage = "Bu alan boş geçilemez.")]
        public int ders_no { get; set; }
        [Required(ErrorMessage = "Bu alan boş geçilemez.")]
        public string ders_adi { get; set; }
        [Required(ErrorMessage = "Bu alan boş geçilemez.")]
        public string ders_hocasi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OgrenciDers> OgrenciDers { get; set; }
    }
}
