//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OkulOtomasyonu.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class OgrenciDers
    {
        public int id { get; set; }
        public int[] ders_id2 { get; set; }
        public Nullable<int> ders_id { get; set; }
        public Nullable<int> ogrenci_id { get; set; }
    
        public virtual Dersler Dersler { get; set; }
        public virtual Ogrenciler Ogrenciler { get; set; }
    }
}
