//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OkulOtomasyonu.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Text;

    public partial class Ogrenciler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ogrenciler()
        {
            this.OgrenciDers = new HashSet<OgrenciDers>();
        }
      
        public int id { get; set; }
        
        [Required(ErrorMessage = "Bu alan boş geçilemez.")]
        public string adi { get; set; }
        [Required(ErrorMessage = "Bu alan boş geçilemez.")]
        public string soyadi { get; set; }
        [Required(ErrorMessage = "Bu alan boş geçilemez.")]
        public string tc_no { get; set; }
        [Required(ErrorMessage = "Bu alan boş geçilemez.")]
        public string o_no { get; set; }
        [Required(ErrorMessage = "Bu alan boş geçilemez.")]
        [DataType(DataType.Time)]
        public System.DateTime d_tarihi { get; set; }
        [Required(ErrorMessage = "Bu alan boş geçilemez.")]
        public string adres { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OgrenciDers> OgrenciDers { get; set; }
        public object Title { get; internal set; }
    }
}
