//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OkulOtomasyonu.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Yoneticiler
    {
        public int id { get; set; }
        [Required(ErrorMessage = "Bu alan boş geçilemez.")]
        public string k_adi { get; set; }
        [Required(ErrorMessage = "Bu alan boş geçilemez.")]
        [StringLength(50, ErrorMessage = "Şifre en fazla {1}, en az {2} karakter uzunluğunda olmalıdır!", MinimumLength = 6)]
        [DataType(DataType.Password)]
        public string sifre { get; set; }
        [Required(ErrorMessage = "Bu alan boş geçilemez.")]
        [System.Web.Mvc.Compare("sifre", ErrorMessage = "İki şifre eşleşmiyor!")]
        [DataType(DataType.Password)]
        public string sifre2 { get; set; }
        [Required(ErrorMessage = "Bu alan boş geçilemez.")]
        [RegularExpression(@"^([a-zA-Z0-9_\-\.]+)@((\[[0-9]{1,3}" +
                           @"\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([a-zA-Z0-9\-]+\" +
                           @".)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$",
                           ErrorMessage = "Email adresi geçersiz")]
        public string email { get; set; }
        [Required(ErrorMessage = "Bu alan boş geçilemez.")]
        public string gizlisoru { get; set; }
        [Required(ErrorMessage = "Bu alan boş geçilemez.")]
        public string gizlicevap { get; set; }
        [Required(ErrorMessage = "Bu alan boş geçilemez.")]
        [DataType(DataType.Time)]
        public Nullable<System.DateTime> songiristarihi { get; set; }
    }
}
